/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        "header": string;
    }
    interface MyFirstGridComponent {
        "apikey": string;
        "privatekey": string;
        "url": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyFirstGridComponentElement extends Components.MyFirstGridComponent, HTMLStencilElement {
    }
    var HTMLMyFirstGridComponentElement: {
        prototype: HTMLMyFirstGridComponentElement;
        new (): HTMLMyFirstGridComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-first-grid-component": HTMLMyFirstGridComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        "header"?: string;
    }
    interface MyFirstGridComponent {
        "apikey"?: string;
        "privatekey"?: string;
        "url"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-first-grid-component": MyFirstGridComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-first-grid-component": LocalJSX.MyFirstGridComponent & JSXBase.HTMLAttributes<HTMLMyFirstGridComponentElement>;
        }
    }
}
